[package]
name = "graph-window"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.9", features = ["v4_14"] }
gtk4-layer-shell = "0.4"
cairo-rs = { version = "0.20", features = ["v1_18"] }
glib = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
